### ISSUE TITLE
Bulk API endpoint returns 500 when requested without trailing slash

### ISSUE THREAD

**Issue by ondryaso** [CESNET/NERD#34]
The bulk IP address query endpoint must be accessed with a trailing slash: `<base_url>/ip/bulk/`, as documented in the [wiki](https://github.com/CESNET/NERD/wiki/API#bulk-querying). When invoking the endpoint without the trailing slash, the response is always `{"err_n": 500, "error": "Internal Server Error"}`. 

Can be reproduced with:
```
curl -H "Authorization: TOKEN" -H "Content-Type: application/octet-stream" https://nerd.cesnet.cz/nerd/api/v1/ip/bulk --data "ZZZZ"
```

This is most certainly incorrect behaviour. The response should at least be a 404, perhaps 400. Though, I would personally consider "bulk" to be _the_ resource that is being accessed; that would mean that _not_ having a trailing slash would be the _right_ way to access it. Practically, to ensure compatibility, I think both variants should work equally...

**Comment by vaclavbartos** [comment]
Thanks for reporting this. I agree it would be more correct without the trailing slash. And definitely it shouldn't fail with 500. 

Fortunatelly, the fix was trivial - it now works both with and without the trailing slash (fixed in 787560d, tested and deployed on the main server).

By the way, the bulk endpoint was written several years ago for some experiments, it apparenlty wasn't well tested and AFAIK nobody used it regularly since then. If you run into any other issues or have any suggestion to improve it, let me know.
